name: CI/CD Test Pipeline

on:
    push:
        branches:
            - main
        paths:
            - '**/*.py'
            - 'requirements.txt'
            - '.github/workflows/**'
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  pytest
