name: Token check

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner, repo = context.repo.repo;
            const sha = context.sha;
            const tag = `refs/tags/release/dev/default/test-${Date.now()}`;
            try {
              await github.rest.git.createRef({ owner, repo, ref: tag, sha });
              core.info(`✅ Created tag ${tag}`);
              await github.rest.git.deleteRef({ owner, repo, ref: tag.replace('refs/','') });
              core.info('✅ Deleted tag');
            } catch (e) {
              core.setFailed(`❌ Token cannot create tags: ${e.message}`);
            }