name: Token check

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner, repo = context.repo.repo;
            const sha = context.sha;
            const tag = `refs/tags/release/dev/default/3.0.5}`;
            try {
              await github.rest.git.createRef({ owner, repo, ref: tag, sha });
              core.info(`✅ Created tag ${tag}`);
              await github.rest.git.deleteRef({ owner, repo, ref: tag.replace('refs/','') });
              core.info('✅ Deleted tag');
            } catch (e) {
              core.setFailed(`❌ Token cannot create tags: ${e.message}`);
            }
      
      - name: Debug tag protection rules
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner, repo = context.repo.repo;
            try {
                const { data } = await github.request('GET /repos/{owner}/{repo}/tags/protection', { owner, repo });
                if (!data?.length) {
                core.info('No tag protection rules configured.');
                } else {
                core.info('Tag protection rules:');
                for (const r of data) {
                    core.info(`- pattern: ${r.pattern} | block_creations: ${!!r.block_creations}`);
                }
                }
            } catch (e) {
                core.warning(`Could not list tag protection rules: ${e.message}`);
            }
