name: PR Label Gate

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, reopened, ready_for_review]
    branches: [development]

permissions:
  contents: read
  pull-requests: read

jobs:
  require-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate labels (enforced)
        id: validate
        uses: ./.github/actions/validate-release-labels
        with:
          enforce: "true"

      # Belt & suspenders: if the validator flagged invalid, fail explicitly.
      - name: Enforce invalid labeling
        if: steps.validate.outputs.invalid == 'true'
        run: |
          echo "::error::${{ steps.validate.outputs.reason }}"
          exit 1

      # Optional: visibility when valid
      - name: Summary
        if: steps.validate.outputs.skip != 'true'
        run: |
          echo "Release bump: ${{ steps.validate.outputs.bump }}"
          echo "Tenants: ${{ steps.validate.outputs.tenants }}"
