name: PR Label Gate

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, reopened, ready_for_review]
    branches: [development]

permissions:
  pull-requests: read

jobs:
  require-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Validate labels (enforced)
        id: validate
        uses: ./.github/actions/validate-release-labels
        with:
          enforce: "true"

      # Optional: echo what we resolved (for visibility when valid)
      - name: Summary
        if: success() && steps.validate.outputs.skip == 'false'
        run: |
          echo "Release bump: ${{ steps.validate.outputs.bump }}"
          echo "Tenants: ${{ steps.validate.outputs.tenants }}"