name: Validate release labels

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, ready_for_review]
    branches: [development]

permissions:
  pull-requests: read
  statuses: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check required labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (pr.draft) {
              core.notice('PR is draft; skipping validation.');
              return;
            }
            const labels = (pr.labels || []).map(l => l.name);
            const rel = labels.find(l => /^release:(patch|minor|major|none)$/.test(l));
            const ten = labels.find(l => /^tenant:(default|csu|both)$/.test(l));

            let ok = true;
            if (!rel) { core.error('Missing release:* label (patch|minor|major|none)'); ok = false; }
            if (!ten) { core.error('Missing tenant:* label (default|csu|both)'); ok = false; }

            if (!ok) core.setFailed('Required labels not present.');
